# Generated by Django 2.0.13 on 2019-03-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='slug',
            field=models.SlugField(default='receipt1', unique=True),
            preserve_default=False,
        ),
    ]
