# Generated by Django 2.0.13 on 2019-03-06 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_receipt_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='slug',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL),
        ),
    ]
